spring:
  application:
    name: multithreading

  datasource:
    url: jdbc:postgresql://localhost:5432/multithreading
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver